# Generated by Django 4.2.11 on 2024-04-04 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='ItemImages')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='ItemImages')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='ItemImages')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='ItemImages')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='ItemImages')),
                ('name', models.TextField(default='Component')),
                ('description', models.TextField(default='Description')),
                ('price', models.IntegerField()),
                ('price_before', models.IntegerField()),
                ('category', models.JSONField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('other', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PwdReset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('email_to', models.TextField(blank=True, null=True)),
                ('email_from', models.TextField(blank=True, default='wamso2496@gmail.com', null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
